"""Event taxonomy and error classification for daemon observability."""

from enum import StrEnum


class EventLevel(StrEnum):
    INFO = "INFO"
    WARN = "WARN"
    ERROR = "ERROR"


class EventCategory(StrEnum):
    STATE_TRANSITION = "STATE_TRANSITION"
    TRANSITION_VIOLATION = "TRANSITION_VIOLATION"
    BOOTSTRAP_FAILURE = "BOOTSTRAP_FAILURE"
    STAGING_INCONSISTENT = "STAGING_INCONSISTENT"
    SESSION_DEDUP_APPLIED = "SESSION_DEDUP_APPLIED"
    LOCAL_DEDUP_APPLIED = "LOCAL_DEDUP_APPLIED"
    QUEUE_UPLOAD_PREPARED = "QUEUE_UPLOAD_PREPARED"
    JOB_LOCAL_COMPLETED = "JOB_LOCAL_COMPLETED"
    RECOVERY_DISPATCH_LIMIT = "RECOVERY_DISPATCH_LIMIT"
    TICK_NOOP = "TICK_NOOP"
    COPY_RETRY_SCHEDULED = "COPY_RETRY_SCHEDULED"
    COPY_SOURCE_MISSING = "COPY_SOURCE_MISSING"
    COPY_PERMISSION_DENIED = "COPY_PERMISSION_DENIED"
    COPY_IO_ERROR = "COPY_IO_ERROR"
    HASHING_INCONSISTENT = "HASHING_INCONSISTENT"
    HASH_RETRY_SCHEDULED = "HASH_RETRY_SCHEDULED"
    HASH_SOURCE_MISSING = "HASH_SOURCE_MISSING"
    HASH_PERMISSION_DENIED = "HASH_PERMISSION_DENIED"
    HASH_IO_ERROR = "HASH_IO_ERROR"
    HANDSHAKE_CLASSIFIED = "HANDSHAKE_CLASSIFIED"
    HANDSHAKE_RETRY_SCHEDULED = "HANDSHAKE_RETRY_SCHEDULED"
    HANDSHAKE_INVALID_RESPONSE = "HANDSHAKE_INVALID_RESPONSE"
    UPLOAD_FILE_STORED = "UPLOAD_FILE_STORED"
    UPLOAD_RETRY_SCHEDULED = "UPLOAD_RETRY_SCHEDULED"
    SERVER_VERIFY_COMPLETED = "SERVER_VERIFY_COMPLETED"
    SERVER_VERIFY_RETRY_SCHEDULED = "SERVER_VERIFY_RETRY_SCHEDULED"
    POST_UPLOAD_VERIFY_COMPLETED = "POST_UPLOAD_VERIFY_COMPLETED"
    CLEANUP_STAGING_APPLIED = "CLEANUP_STAGING_APPLIED"
    JOB_REMOTE_COMPLETED = "JOB_REMOTE_COMPLETED"
    INVARIANT_VIOLATION = "INVARIANT_VIOLATION"
    RECOVERY_BOUNDARY_UNIMPLEMENTED = "RECOVERY_BOUNDARY_UNIMPLEMENTED"
    RECOVERY_STOPPED_ERROR = "RECOVERY_STOPPED_ERROR"


def classify_copy_error(exc: OSError) -> EventCategory:
    if isinstance(exc, FileNotFoundError):
        return EventCategory.COPY_SOURCE_MISSING
    if isinstance(exc, PermissionError):
        return EventCategory.COPY_PERMISSION_DENIED
    return EventCategory.COPY_IO_ERROR


def classify_hash_error(exc: OSError) -> EventCategory:
    if isinstance(exc, FileNotFoundError):
        return EventCategory.HASH_SOURCE_MISSING
    if isinstance(exc, PermissionError):
        return EventCategory.HASH_PERMISSION_DENIED
    return EventCategory.HASH_IO_ERROR
