"""Compatibility exports for clientd networking helpers."""

from .networking_adapter import NetworkManagerAdapter
from .networking_nmcli import (
    _apply_sta_probe_override,
    _classify_upstream_status,
    _extract_http_status_code,
    _normalize_connectivity_value,
    _normalize_failure,
    _normalize_never_default_value,
    _probe_sta_interface_connectivity,
    _run_nmcli,
    _safe_signal_value,
    _select_sta_connectivity,
    _sta_profile_name,
    parse_nmcli_multiline,
)
from .networking_types import (
    DEFAULT_AP_PASSWORD,
    DEFAULT_AP_PROFILE_NAME,
    DEFAULT_AP_SSID,
    AccessPointProfile,
    NetworkDevice,
    NetworkGeneral,
    NetworkManagerError,
    NetworkStatusSnapshot,
    OperatorError,
    WifiNetwork,
)

__all__ = [
    "AccessPointProfile",
    "DEFAULT_AP_PASSWORD",
    "DEFAULT_AP_PROFILE_NAME",
    "DEFAULT_AP_SSID",
    "NetworkDevice",
    "NetworkGeneral",
    "NetworkManagerAdapter",
    "NetworkManagerError",
    "NetworkStatusSnapshot",
    "OperatorError",
    "WifiNetwork",
    "_apply_sta_probe_override",
    "_classify_upstream_status",
    "_extract_http_status_code",
    "_normalize_connectivity_value",
    "_normalize_failure",
    "_normalize_never_default_value",
    "_probe_sta_interface_connectivity",
    "_run_nmcli",
    "_safe_signal_value",
    "_select_sta_connectivity",
    "_sta_profile_name",
    "parse_nmcli_multiline",
]
