"""Canonical client states used by the daemon.

This mirrors the v1 state machine document so code can reference explicit states.
"""

from enum import StrEnum


class ClientState(StrEnum):
    BOOTSTRAP = "BOOTSTRAP"
    IDLE = "IDLE"
    WAIT_MEDIA = "WAIT_MEDIA"
    DISCOVERING = "DISCOVERING"
    STAGING_COPY = "STAGING_COPY"
    HASHING = "HASHING"
    DEDUP_SESSION_SHA = "DEDUP_SESSION_SHA"
    DEDUP_LOCAL_SHA = "DEDUP_LOCAL_SHA"
    QUEUE_UPLOAD = "QUEUE_UPLOAD"
    WAIT_NETWORK = "WAIT_NETWORK"
    UPLOAD_PREPARE = "UPLOAD_PREPARE"
    UPLOAD_FILE = "UPLOAD_FILE"
    SERVER_VERIFY = "SERVER_VERIFY"
    POST_UPLOAD_VERIFY = "POST_UPLOAD_VERIFY"
    REUPLOAD_OR_QUARANTINE = "REUPLOAD_OR_QUARANTINE"
    CLEANUP_STAGING = "CLEANUP_STAGING"
    JOB_COMPLETE_REMOTE = "JOB_COMPLETE_REMOTE"
    JOB_COMPLETE_LOCAL = "JOB_COMPLETE_LOCAL"
    VERIFY_IDLE = "VERIFY_IDLE"
    VERIFY_HASH = "VERIFY_HASH"
    PAUSED_STORAGE = "PAUSED_STORAGE"
    ERROR_FILE = "ERROR_FILE"
    ERROR_JOB = "ERROR_JOB"
    ERROR_DAEMON = "ERROR_DAEMON"


class FileStatus(StrEnum):
    DISCOVERED = "DISCOVERED"
    NEEDS_RETRY_COPY = "NEEDS_RETRY_COPY"
    STAGED = "STAGED"
    NEEDS_RETRY_HASH = "NEEDS_RETRY_HASH"
    HASHED = "HASHED"
    READY_TO_UPLOAD = "READY_TO_UPLOAD"
    UPLOADED = "UPLOADED"
    VERIFY_RUNNING = "VERIFY_RUNNING"
    VERIFIED_REMOTE = "VERIFIED_REMOTE"
    DUPLICATE_SHA_GLOBAL = "DUPLICATE_SHA_GLOBAL"
    DUPLICATE_SHA_LOCAL = "DUPLICATE_SHA_LOCAL"
    DUPLICATE_SESSION_SHA = "DUPLICATE_SESSION_SHA"
    ERROR_FILE = "ERROR_FILE"
    QUARANTINED_LOCAL = "QUARANTINED_LOCAL"
